//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Parcial2Entities1 : DbContext
    {
        public DB_Parcial2Entities1()
            : base("name=DB_Parcial2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TB_Clientes> TB_Clientes { get; set; }
        public DbSet<TB_DetallePedidos> TB_DetallePedidos { get; set; }
        public DbSet<TB_Ingredientes> TB_Ingredientes { get; set; }
        public DbSet<TB_Inventario> TB_Inventario { get; set; }
        public DbSet<TB_Mantenimientos> TB_Mantenimientos { get; set; }
        public DbSet<TB_Modo> TB_Modo { get; set; }
        public DbSet<TB_Pedidos> TB_Pedidos { get; set; }
        public DbSet<TB_Precios> TB_Precios { get; set; }
        public DbSet<TB_Premios> TB_Premios { get; set; }
        public DbSet<TB_Productos> TB_Productos { get; set; }
        public DbSet<TB_Repartidores> TB_Repartidores { get; set; }
        public DbSet<TB_Scooter> TB_Scooter { get; set; }
        public DbSet<TB_Tamanio> TB_Tamanio { get; set; }
        public DbSet<TB_TipoProductos> TB_TipoProductos { get; set; }
        public DbSet<TB_Ventas> TB_Ventas { get; set; }
    }
}
