//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Clientes
    {
        public TB_Clientes()
        {
            this.TB_DetallePedidos = new HashSet<TB_DetallePedidos>();
            this.TB_Pedidos = new HashSet<TB_Pedidos>();
            this.TB_Inventario = new HashSet<TB_Inventario>();
        }
    
        public int Cliente_ID { get; set; }
        public string Cliente_Nombre { get; set; }
        public string Cliente_Direccion { get; set; }
        public decimal Cliente_Telefono { get; set; }
    
        public virtual ICollection<TB_DetallePedidos> TB_DetallePedidos { get; set; }
        public virtual ICollection<TB_Pedidos> TB_Pedidos { get; set; }
        public virtual ICollection<TB_Inventario> TB_Inventario { get; set; }
    }
}
