//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Inventario
    {
        public int Inventario_ID { get; set; }
        public int ClienteID_Inventario { get; set; }
        public int Inventario_Existencia { get; set; }
    
        public virtual TB_Clientes TB_Clientes { get; set; }
    }
}
