//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Mantenimientos
    {
        public TB_Mantenimientos()
        {
            this.TB_Scooter = new HashSet<TB_Scooter>();
        }
    
        public int Mantenimiento_ID { get; set; }
        public string Mantenimiento_Descripcion { get; set; }
        public int Mantenimiento_KM { get; set; }
    
        public virtual ICollection<TB_Scooter> TB_Scooter { get; set; }
    }
}
