//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Modo
    {
        public TB_Modo()
        {
            this.TB_Pedidos = new HashSet<TB_Pedidos>();
        }
    
        public int Modo_ID { get; set; }
        public string Modo_Modo { get; set; }
    
        public virtual ICollection<TB_Pedidos> TB_Pedidos { get; set; }
    }
}
