//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Premios
    {
        public TB_Premios()
        {
            this.TB_Pedidos = new HashSet<TB_Pedidos>();
        }
    
        public int Premio_ID { get; set; }
        public string Premio_Premio { get; set; }
        public string Premio_Descripcion { get; set; }
    
        public virtual ICollection<TB_Pedidos> TB_Pedidos { get; set; }
    }
}
