//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Precios
    {
        public TB_Precios()
        {
            this.TB_Ingredientes = new HashSet<TB_Ingredientes>();
            this.TB_Productos = new HashSet<TB_Productos>();
            this.TB_Ventas = new HashSet<TB_Ventas>();
        }
    
        public int Precio_ID { get; set; }
        public int Precio_Precio { get; set; }
    
        public virtual ICollection<TB_Ingredientes> TB_Ingredientes { get; set; }
        public virtual ICollection<TB_Productos> TB_Productos { get; set; }
        public virtual ICollection<TB_Ventas> TB_Ventas { get; set; }
    }
}
