//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Productos
    {
        public TB_Productos()
        {
            this.TB_Pedidos = new HashSet<TB_Pedidos>();
        }
    
        public int Producto_ID { get; set; }
        public int IngredientesID_Producto { get; set; }
        public string Producto_Nombre { get; set; }
        public int PrecioID_Producto { get; set; }
        public int TipoProducto_ID { get; set; }
        public int TamanioID_Producto { get; set; }
    
        public virtual TB_Ingredientes TB_Ingredientes { get; set; }
        public virtual ICollection<TB_Pedidos> TB_Pedidos { get; set; }
        public virtual TB_Precios TB_Precios { get; set; }
        public virtual TB_Tamanio TB_Tamanio { get; set; }
        public virtual TB_TipoProductos TB_TipoProductos { get; set; }
    }
}
