//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Pedidos
    {
        public int Pedido_ID { get; set; }
        public int ProductoID_Pedido { get; set; }
        public int TipoVentaID_Pedido { get; set; }
        public int Producto_Total { get; set; }
        public int ModoID_Pedido { get; set; }
        public int ClienteID_Pedido { get; set; }
        public int PremioID_Producto { get; set; }
        public Nullable<int> RepartidorID_Pedido { get; set; }
    
        public virtual TB_Clientes TB_Clientes { get; set; }
        public virtual TB_Modo TB_Modo { get; set; }
        public virtual TB_Premios TB_Premios { get; set; }
        public virtual TB_Productos TB_Productos { get; set; }
        public virtual TB_Repartidores TB_Repartidores { get; set; }
        public virtual TB_Ventas TB_Ventas { get; set; }
    }
}
