//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Scooter
    {
        public TB_Scooter()
        {
            this.TB_Repartidores = new HashSet<TB_Repartidores>();
        }
    
        public int Scooter_ID { get; set; }
        public string Scooter_Descripcion { get; set; }
        public int MantenimientoID_Scooter { get; set; }
    
        public virtual TB_Mantenimientos TB_Mantenimientos { get; set; }
        public virtual ICollection<TB_Repartidores> TB_Repartidores { get; set; }
    }
}
