//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TipoProductos
    {
        public TB_TipoProductos()
        {
            this.TB_Productos = new HashSet<TB_Productos>();
        }
    
        public int TipoP_ID { get; set; }
        public string TipoP_Tipo { get; set; }
    
        public virtual ICollection<TB_Productos> TB_Productos { get; set; }
    }
}
