//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Ventas
    {
        public TB_Ventas()
        {
            this.TB_Pedidos = new HashSet<TB_Pedidos>();
        }
    
        public int Venta_ID { get; set; }
        public int PrecioID_Venta { get; set; }
        public int Venta_Precio { get; set; }
    
        public virtual ICollection<TB_Pedidos> TB_Pedidos { get; set; }
        public virtual TB_Precios TB_Precios { get; set; }
    }
}
